stages:
  - debian
  - alpine
  - fpm

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: edbizarro/gitlab-ci-pipeline-php

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

Debian 7.2:
  stage: debian
  variables:
    IMAGE_VERSION: "7.2"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.2/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g goss-7.2.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:latest
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:7
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:7
    - docker push $NAMESPACE:latest
  when: always

Debian 7.1:
  stage: debian
  variables:
    IMAGE_VERSION: "7.1"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.1/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

Debian 7.0:
  stage: debian
  variables:
    IMAGE_VERSION: "7.0"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.0/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

Alpine 7.2:
  stage: alpine
  variables:
    IMAGE_VERSION: "7.2-alpine"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.2/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g goss-7.2.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:alpine
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:alpine
  when: always

Alpine 7.2 LST:
  stage: alpine
  variables:
    IMAGE_VERSION: "7.2-alpine-lts"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.2/alpine/Dockerfile-lts .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g goss-7.2.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:alpine-lts
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:alpine-lts
  when: always

Alpine 7.1:
  stage: alpine
  variables:
    IMAGE_VERSION: "7.1-alpine"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.1/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

Alpine 7.1 LTS:
  stage: alpine
  variables:
    IMAGE_VERSION: "7.1-alpine-lts"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.1/alpine/Dockerfile-lts .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

Alpine 7.0:
  stage: alpine
  variables:
    IMAGE_VERSION: "7.0-alpine"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.0/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

Alpine 7.0 LTS:
  stage: alpine
  variables:
    IMAGE_VERSION: "7.0-alpine-lts"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.0/alpine/Dockerfile-lts .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

FPM 7.0:
  stage: fpm
  variables:
    IMAGE_VERSION: "7.0-fpm"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.0/fpm/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

FPM 7.1:
  stage: fpm
  variables:
    IMAGE_VERSION: "7.1-fpm"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.1/fpm/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

FPM 7.2:
  stage: fpm
  variables:
    IMAGE_VERSION: "7.2-fpm"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.2/fpm/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g goss-7.2.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:fpm
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:fpm
  when: always
