stages:
  - build
  - build-chromium
  - publish
  - test

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: edbizarro/gitlab-ci-pipeline-php

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

Debian 8.0:
  stage: build
  variables:
    IMAGE_VERSION: "8.0"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/$IMAGE_VERSION/Dockerfile .
    - docker run -t --rm edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION -m
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-$IMAGE_VERSION.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:latest
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:8
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:8
    - docker push $NAMESPACE:latest
  when: always

Debian 7.4:
  stage: build
  variables:
    IMAGE_VERSION: "7.4"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/$IMAGE_VERSION/Dockerfile .
    - docker run -t --rm edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION -m
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-$IMAGE_VERSION.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:7
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:7
  when: always

Debian 7.3:
  stage: build
  variables:
    IMAGE_VERSION: "7.3"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/$IMAGE_VERSION/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-$IMAGE_VERSION.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION

  when: always


Alpine 8.0:
  stage: build
  variables:
    IMAGE_VERSION: "8.0-alpine"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.0/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-8.0.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:alpine
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:alpine
  when: always

Alpine 7.4:
  stage: build
  variables:
    IMAGE_VERSION: "7.4-alpine"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.4/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.4.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

Alpine 7.4 LTS:
  stage: build
  variables:
    IMAGE_VERSION: "7.4-alpine-lts"
  script:
    - docker pull php:7.4-alpine || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.4/alpine/Dockerfile-lts .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.2-3-lts.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:alpine-lts
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:alpine-lts
  when: always

Alpine 7.3:
  stage: build
  variables:
    IMAGE_VERSION: "7.3-alpine"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.3/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.3.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

Alpine 7.3 LTS:
  stage: build
  variables:
    IMAGE_VERSION: "7.3-alpine-lts"
  script:
    - docker pull php:7.3-alpine || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.3/alpine/Dockerfile-lts .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.2-3-lts.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always


FPM 8.0:
  stage: build
  variables:
    IMAGE_VERSION: "8.0-fpm"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.0/fpm/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-8.0.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:fpm
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:fpm
  when: always

FPM 7.4:
  stage: build
  variables:
    IMAGE_VERSION: "7.4-fpm"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.4/fpm/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.4.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always


FPM 7.3:
  stage: build
  variables:
    IMAGE_VERSION: "7.3-fpm"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.3/fpm/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.3.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always


Chromium 8.0:
  stage: build-chromium
  variables:
    IMAGE_VERSION: "8.0-chromium"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.0/chromium/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-8.0.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always
  dependencies:
    - Debian 8.0


Chromium 7.4:
  stage: build-chromium
  variables:
    IMAGE_VERSION: "7.4-chromium"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.4/chromium/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-7.4.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always
  dependencies:
    - Debian 7.4

Chromium 7.3:
  stage: build-chromium
  variables:
    IMAGE_VERSION: "7.3-chromium"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.3/chromium/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-7.3.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always
  dependencies:
    - Debian 7.3
